### ISSUE TITLE
How to add multiple servers to query

### ISSUE THREAD

**Issue by XDqrkneZ** [Muqsit/NetworkQuery#1]
I have 3 servers and I want to add them all to network.yml, but how?

**Comment by Muqsit** [comment]
```yaml
---
enable: true
networks:
- - spirit.cosmicpe.me
  - 19132
- - ice.cosmicpe.me
  - 19132
- - jungle.cosmicpe.me
  - 19132
- - demon.cosmicpe.me
  - 19132
- - dream.cosmicpe.me
  - 19132
- - alien.cosmicpe.me
  - 19132
- - pleb.cosmicpe.me
  - 19132
...
```
